<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Happy Birthday</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h1>Happy Birthday, [ VARSHA ]!</h1>
        <p>Wishing you a day filled with love, joy, and happiness!</p>
        <button onclick="playMusic()">Play Birthday Song</button>
    </div>
    <audio id="birthdaySong" src="birthday-song.mp3"></audio>
    <script src="script.js"></script>
</body>
</html>
body {
    background-color: black;
    background-image: url('background-image.jpg');
    background-size: cover;
    background-position: center;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
    font-family: 'Arial', sans-serif;
}

.container {
    text-align: center;
    background: rgba(255, 239, 213, 0.9);
    padding: 30px;
    border-radius: 15px;
    box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
    max-width: 90%;
    margin: 0 10px;
}

h1 {
    color: #ff6347;
    font-size: 2.5em;
    margin-bottom: 20px;
}

p {
    font-size: 1.2em;
    margin-bottom: 30px;
}

button {
    background-color: black;
    color: white;
    padding: 15px 30px;
    font-size: 1em;
    border: none;
    border-radius: 10px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

button:hover {
    background-color: #ff4500;
}

@media (min-width: 600px) {
    h1 {
        font-size: 3em;
    }

    p {
        font-size: 1.5em;
    }

    button {
        font-size: 1.2em;
    }
}
function playMusic() {
    var audio = document.getElementById('birthdaySong');
    audio.play();
}
